"""Add interests and skills to Post model

Revision ID: 011c9c2ce38c
Revises: 18406a2c848d
Create Date: 2024-09-27 20:26:25.774215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011c9c2ce38c'
down_revision = '18406a2c848d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('skills')
        batch_op.drop_column('interests')

    # ### end Alembic commands ###
