"""Added ConnectionRequest model

Revision ID: 3aee4165ae1f
Revises: 66fb10d42b69
Create Date: 2024-10-02 01:17:26.127572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aee4165ae1f'
down_revision = '66fb10d42b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection_request', schema=None) as batch_op:
        batch_op.alter_column('from_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('to_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('date_sent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_sent', sa.DATETIME(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('to_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('from_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
