"""Add interests and skills to User model

Revision ID: f16ab8d9f599
Revises: 011c9c2ce38c
Create Date: 2024-09-28 11:29:43.545999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16ab8d9f599'
down_revision = '011c9c2ce38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('skills')
        batch_op.drop_column('interests')

    # ### end Alembic commands ###
